# Generated by Django 6.0.6 on 2026-06-18 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_popular',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_recommended',
        ),
    ]
